// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: privacy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnonymizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputPath     string                 `protobuf:"bytes,1,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	Epsilon       float32                `protobuf:"fixed32,2,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
	Delta         float32                `protobuf:"fixed32,3,opt,name=delta,proto3" json:"delta,omitempty"`
	DetectPii     bool                   `protobuf:"varint,4,opt,name=detect_pii,json=detectPii,proto3" json:"detect_pii,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnonymizeRequest) Reset() {
	*x = AnonymizeRequest{}
	mi := &file_privacy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonymizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonymizeRequest) ProtoMessage() {}

func (x *AnonymizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonymizeRequest.ProtoReflect.Descriptor instead.
func (*AnonymizeRequest) Descriptor() ([]byte, []int) {
	return file_privacy_proto_rawDescGZIP(), []int{0}
}

func (x *AnonymizeRequest) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *AnonymizeRequest) GetEpsilon() float32 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *AnonymizeRequest) GetDelta() float32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *AnonymizeRequest) GetDetectPii() bool {
	if x != nil {
		return x.DetectPii
	}
	return false
}

type AnonymizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputPath    string                 `protobuf:"bytes,1,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	PrivacyScore  float32                `protobuf:"fixed32,2,opt,name=privacy_score,json=privacyScore,proto3" json:"privacy_score,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	PiiReport     map[string]string      `protobuf:"bytes,4,rep,name=pii_report,json=piiReport,proto3" json:"pii_report,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnonymizeResponse) Reset() {
	*x = AnonymizeResponse{}
	mi := &file_privacy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonymizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonymizeResponse) ProtoMessage() {}

func (x *AnonymizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonymizeResponse.ProtoReflect.Descriptor instead.
func (*AnonymizeResponse) Descriptor() ([]byte, []int) {
	return file_privacy_proto_rawDescGZIP(), []int{1}
}

func (x *AnonymizeResponse) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *AnonymizeResponse) GetPrivacyScore() float32 {
	if x != nil {
		return x.PrivacyScore
	}
	return 0
}

func (x *AnonymizeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnonymizeResponse) GetPiiReport() map[string]string {
	if x != nil {
		return x.PiiReport
	}
	return nil
}

var File_privacy_proto protoreflect.FileDescriptor

const file_privacy_proto_rawDesc = "" +
	"\n" +
	"\rprivacy.proto\x12\aprivacy\"\x80\x01\n" +
	"\x10AnonymizeRequest\x12\x1d\n" +
	"\n" +
	"input_path\x18\x01 \x01(\tR\tinputPath\x12\x18\n" +
	"\aepsilon\x18\x02 \x01(\x02R\aepsilon\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x02R\x05delta\x12\x1d\n" +
	"\n" +
	"detect_pii\x18\x04 \x01(\bR\tdetectPii\"\xf9\x01\n" +
	"\x11AnonymizeResponse\x12\x1f\n" +
	"\voutput_path\x18\x01 \x01(\tR\n" +
	"outputPath\x12#\n" +
	"\rprivacy_score\x18\x02 \x01(\x02R\fprivacyScore\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12H\n" +
	"\n" +
	"pii_report\x18\x04 \x03(\v2).privacy.AnonymizeResponse.PiiReportEntryR\tpiiReport\x1a<\n" +
	"\x0ePiiReportEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012[\n" +
	"\x0ePrivacyService\x12I\n" +
	"\x0eProcessDataset\x12\x19.privacy.AnonymizeRequest\x1a\x1a.privacy.AnonymizeResponse\"\x00B\x0fZ\rbackend-go/pbb\x06proto3"

var (
	file_privacy_proto_rawDescOnce sync.Once
	file_privacy_proto_rawDescData []byte
)

func file_privacy_proto_rawDescGZIP() []byte {
	file_privacy_proto_rawDescOnce.Do(func() {
		file_privacy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_privacy_proto_rawDesc), len(file_privacy_proto_rawDesc)))
	})
	return file_privacy_proto_rawDescData
}

var file_privacy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_privacy_proto_goTypes = []any{
	(*AnonymizeRequest)(nil),  // 0: privacy.AnonymizeRequest
	(*AnonymizeResponse)(nil), // 1: privacy.AnonymizeResponse
	nil,                       // 2: privacy.AnonymizeResponse.PiiReportEntry
}
var file_privacy_proto_depIdxs = []int32{
	2, // 0: privacy.AnonymizeResponse.pii_report:type_name -> privacy.AnonymizeResponse.PiiReportEntry
	0, // 1: privacy.PrivacyService.ProcessDataset:input_type -> privacy.AnonymizeRequest
	1, // 2: privacy.PrivacyService.ProcessDataset:output_type -> privacy.AnonymizeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_privacy_proto_init() }
func file_privacy_proto_init() {
	if File_privacy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_privacy_proto_rawDesc), len(file_privacy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_privacy_proto_goTypes,
		DependencyIndexes: file_privacy_proto_depIdxs,
		MessageInfos:      file_privacy_proto_msgTypes,
	}.Build()
	File_privacy_proto = out.File
	file_privacy_proto_goTypes = nil
	file_privacy_proto_depIdxs = nil
}
